### ISSUE TITLE
Use Orc.Skia to replace XForms CustomRender in UWP

### ISSUE THREAD

**Issue by JimSEOW** [WildGums/Orc.Skia#1]
Perhaps an example how to use Orc.Skia to use Canvas [of Orc.Skia] for creating custom button, Frame for UWP platform in Xamarin Form to address the need for CustomRender for UWP

**Comment by GeertvanHorrik** [comment]
At the moment we implement SkiaCanvas which supports every dpi mode. I think Xamarin itself also has a XamlCanvas for UWP, but it doesn't actually take care of high-dpi scaling, but you could look into that if you are not interested.

We are planning support for Xamarin.Forms, but we need to be honest and that's not on the short term. Maybe later this year or as a PR.
